- .codeclimate.yml
- .travis.yml
- setup.cfg
modified:   .codeclimate.yml
new file:   .travis.yml
new file:   setup.cfg
> Added travis and codeclimcate configuration

- __init__.py
> add missing __init__ file

- .travis.yml
- requirements.txt
> fix coverage report

- forms/form_offer_preference.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/internship_selection.html
- views/selection.py
Référence Jira : INTERNSHIP-87
> INTERNSHIP-87 warn user when switching internship selection tab without saving

- tests/models/test_internship_offer.py
> Use assertEqual

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- models/internship_choice.py
- templates/fragment/internship_preferences.html
- templates/internship_selection.html
- templatetags/selection_tags.py
- tests/models/test_internship_choice.py
- tests/views/test_main.py
- urls.py
- views/selection.py
Référence Jira : INTERNSHIP-87
> INTERNSHIP-87 keep internships preferences when switching tabs in selection view

- requirements.txt
> Update internship requirements

- models/internship_choice.py
- tests/models/test_internship_choice.py
Référence Jira : INTERNSHIP-173
> INTERNSHIP-173 fix computing number of first choices

- models/score_encoding_utils.py
- templates/api_pagination/pagination.html
- templates/internship_score_encoding_sheet.html
- templatetags/api_pagination.py
- tests/templatetags/test_api_pagination.py
- tests/views/test_api_client.py
- tests/views/test_score_encoding.py
- views/api_client.py
- views/score_encoding.py
> add api pagination to score encoding sheet

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/internship_apd_documentation.html
- templates/internship_score_encoding_form.html
- templates/internship_score_encoding_sheet.html
Référence Jira : INTERNSHIP-198
> INTERNSHIP-198 add APDs documentation

- models/enums/user_account_status.py
- tests/views/test_main.py
- views/api_client.py
- views/main.py
Référence Jira : INTERNSHIP-207
> INTERNSHIP-207 activate master user account on first access

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/student_resume.html
- views/resume.py
Référence Jira : INTERNSHIP-200
> INTERNSHIP-200 show internship scores for student

- templates/fragment/validation_confirmation_modal.html
- templates/internship_score_encoding_sheet.html
- templates/internship_student_home.html
- tests/views/test_api_client.py
- tests/views/test_score_encoding.py
- urls.py
- views/api_client.py
- views/resume.py
- views/score_encoding.py
Référence Jira : INTERNSHIP-211 
> INTERNSHIP-211 implement ajax for score validation

- services/internship.py
- tests/services/test_api_client.py
- views/score_encoding.py
Référence Jira : INTERNSHIP-235
> INTERNSHIP-235 align get and update score on sdk

- models/enums/civility.py
- tests/models/test_enums.py
- tests/views/test_resume.py
- views/resume.py
Référence Jira : INTERNSHIP-236
> INTERNSHIP-236 get internship masters from api in student resume

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- templates/internship_score_encoding_form.html
- templates/internship_score_encoding_sheet.html
- tests/services/test_api_client.py
- tests/views/test_score_encoding.py
- views/score_encoding.py
Référence Jira : INTERNSHIP-242
> INTERNSHIP-242 gather response about student presence in score encoding form

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- models/enums/civility.py
- requirements.txt
- services/internship.py
- templates/internship_manage_delegates.html
- templates/internship_master_home.html
- templates/internship_score_encoding_form.html
- templates/internship_score_encoding_sheet.html
- templates/student_resume.html
- templatetags/civility.py
- tests/models/test_enums.py
- tests/services/test_api_client.py
- tests/views/test_master_delegates.py
- tests/views/test_resume.py
- tests/views/test_score_encoding.py
- views/main.py
- views/master_delegates.py
- views/resume.py
- views/score_encoding.py
> Release to master

- models/score_encoding_utils.py
- templates/internship_score_encoding_form.html
- views/score_encoding.py
> INTERNSHIP-231 show apd description on hover

- locale/fr_BE/LC_MESSAGES/django.po
> INTERNSHIP-256 edit translations

- requirements.txt
> OSIS-6002 : requirements sdk

- decorators/cohort_view_decorators.py
- decorators/global_view_decorators.py
- views/main.py
> OSIS-6279 : Use new class-based view for dashboard home

- templates/internship_student_home.html
> Fontawesome

- decorators/cohort_view_decorators.py
- decorators/global_view_decorators.py
- templates/internship_student_home.html
- views/main.py
This reverts commit cc63cb0d1e3fb2a1c2bc2f035d05b4aea9649bdb, reversing
changes made to 86097270cb5f0a28d598cad099b0c2962d22ab0c.
> Revert "Merge pull request #87 from uclouvain/qa"

- decorators/cohort_view_decorators.py
- decorators/global_view_decorators.py
- templates/internship_student_home.html
- views/main.py
Reverts uclouvain/osis-portal-internship#89
> Revert "Revert qa"

- decorators/cohort_view_decorators.py
- decorators/global_view_decorators.py
- templates/internship_student_home.html
- views/main.py
Reverts uclouvain/osis-portal-internship#88
> Release 4.1 : Revert "Revert "Merge pull request #87 from uclouvain/qa""

- decorators/score_encoding_view_decorators.py
- requirements.txt
- tests/services/test_api_client.py
- views/score_encoding.py
> INTERNSHIP-259 include parent specialty in matching allocations

- templates/internship_score_encoding_form.html
> INTERNSHIP-278 transpose apd internship evaluation form using flex container

- templates/internship_master_home.html
> INTERNSHIP-251 fix master/delegates dashboard display

- tests/models/test_internship_choice.py
- tests/models/test_organization.py
- tests/views/test_main.py
- tests/views/test_master_delegates.py
- tests/views/test_score_encoding.py
> [QA] Django32

- tests/models/test_internship_choice.py
- tests/models/test_organization.py
- tests/views/test_main.py
- tests/views/test_master_delegates.py
- tests/views/test_score_encoding.py
> [MASTER] Django32

- requirements.txt
- services/internship.py
- tests/services/test_api_client.py
> Fix service get affectation

- services/internship.py
- tests/services/test_api_client.py
> Fix get affectation dev

- services/internship.py
- tests/services/test_api_client.py
> INTERNSHIP-300 fix service get_affectation

- requirements.txt
> [TEST] Release

- requirements.txt
> [QA] Release

- services/internship.py
> INTERNSHIP-310 increase api limit for retrieving place evaluation items

- requirements.txt
- services/internship.py
> [QA] INTERNSHIP-310 increase api limit for retrieving place evaluation items

- templates/internship_delegate_form.html
- views/master_delegates.py
> INTERNSHIP-312 validate delegates input through django form

- migrations/0009_internship_student_group.py
- migrations/0037_internship_masters_group.py
>  fix migration

- services/internship.py
- templates/place_evaluation_list.html
- views/place_evaluation.py
> Internship 298 to dev

- requirements.txt
- services/internship.py
> [To QA] fix limit for specialties and update sdk

- requirements.txt
- services/internship.py
> [TO QA] Release

- tests/services/test_api_client.py
- views/score_encoding.py
> [To QA] fix periods sorting in select

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- models/score_encoding_utils.py
- requirements.txt
- templates/internship_score_encoding_form.html
- tests/services/test_api_client.py
- views/score_encoding.py
> INTERNSHIP-315 adapt form to includes required APDs

- locale/fr_BE/LC_MESSAGES/django.po
- views/score_encoding.py
> INTERNSHIP-315 fix trans

- models/score_encoding_utils.py
- templates/internship_score_encoding.html
- tests/services/test_api_client.py
- views/score_encoding.py
> Internship 315

- views/resume.py
> INTERNSHIP-325 : fix if no offer

- requirements.txt
- urls.py
> [WIP] Python migration

- templates/place_evaluation_list.html
> INTERNSHIP-330 fix disable place evaluation button

- templates/internship_score_encoding.html
> fix show all periods on internship_score_encoding

- templates/internship_score_encoding.html
> Fix show all periods score encoding

- templates/internship_score_encoding_form_preconcours.html
- templates/internship_score_encoding_sheet.html
- templates/student_resume.html
- views/resume.py
- views/score_encoding.py
> INTERNSHIP-316 save and validate preconcours form + adapt student resume

- templates/student_resume.html
> replace score labels for MG600

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/student_resume.html
> INTERNSHIP-316 fix trans

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/student_resume.html
> INTERNSHIP-316

- requirements.txt
> [DEV] Fix issue with api
